### ISSUE TITLE
Section 2 - Clarify variable definitions

### ISSUE THREAD

**Issue by henry739** [datatrails/draft-bryce-cose-merkle-mountain-range-proofs#2]
In [Section 2 - Conventions and Definitions](https://datatrails.github.io/draft-bryce-cose-merkle-mountain-range-proofs/draft-bryce-cose-merkle-mountain-range-proofs.html#name-conventions-and-definitions) there are opportunities to clarify things:

```
i shall be the index of a node in the MMR
pos shall be i+1
e shall be the zero based index of leaf entry in the MMR
f shall be a leaf value, which is H(x)
h shall be the 1 based tree height
g shall be the 0 based height, h-1
v shall be any node, including a leaf node value, which will be the result of H(x).
S shall be any valid MMR size, and is uniquely identifying for an MMR state
A shall be the the accumulator for any valid MMR size S
R shall be the the sparse accumulator, of [ReyzinYakoubov](https://eprint.iacr.org/2015/718.pdf), for any valid MMR size S
H(x) shall be the SHA-256 digest of any value x
|| shall mean concatenation of raw byte representations of the referenced values.
```

1. Without the context that I already have, I'm not sure its clear from the definition if `e` is the subset of `i` that are leaves, or if `e` is a zero-based enumeration of the leaves.
2. It might be more intuitive to just inline `(h - 1)` rather than adding `g` as an additional variable to remember.
3. Extend the zero-based and one-based descriptions to all of the variables where relevant (e.g. for `i` and `pos`.)
4. Later in the document, `D` is referred to, without a definition - so it might be helpful to add that here.

**Comment by robinbryce** [comment]
I've gone with using almost exclusively `g` or `g+1`. Zero based height indices are what most of the algorithms naturaly want to work with.

I've also made it so that ALL arguments to ALL algorithms accept node indices. 'pos' or size 's' is often used as an internal detail, but is never part of the index. This includes peaks which previously retuend a list of positions.

I think this mostly addresses this. Except for D which I'll address seperately
